spring.application.name=baitap4_qlsp
# C?u hình k?t n?i c? s? d? li?u
spring.datasource.url=jdbc:mysql://localhost:3306/bai5_qlsp
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
